apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache-cli-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache-cli
  template:
    metadata:
      labels:
        app: ganache-cli
    spec:
      containers:
      - name: ganache-cli
        image: ajeyaunoff/ganache:latest
        ports:
        - containerPort: 8545